### ISSUE TITLE
Create an NSubstitute version of EntityFrameworkMock

### ISSUE THREAD

**Issue by pcmichaels** [huysentruitw/entity-framework-mock#1]
I'd like to create an NSubstitute version of this library.  Rather than forking and maintaining a separate code base, I think it would make sense to keep them both in the same repo - and probably the same solution.

My suggection would be that, rather than rename the existing project to EntityFrameworkMock.Moq, you leave it as is, and the new library is called EntityFrameworkSubstitute.

The unit tests and libraries should be able to share common code; although the unit tests will ultimately need to be separated.

**Comment by huysentruitw** [comment]
I was thinking at the same naming convention so we don't break existing projects. But can't figure out a name for the shared library 😃

**Comment by pcmichaels** [comment]
Yeah - hadn’t really thought of that.  Naming is the hardest part of programming :-)

I can think of two options:

1.  The shared library is EntityFrameworkMock.Core, and you either break comparability (it is a new Nuget package, so a new version usually means people aren’t shocked when there are breaking changes), or just leave the library as it is (must admit, this grates a bit).

2. Depending on how generic the core code is, take it into it’s own repo and nuget package.  I like this, but am unclear whether it’ll make sense - depends how much can be separated.  It strikes me that most of what is able to be separated is the data simulator...

**Comment by huysentruitw** [comment]
Since the name of the library is EntityFrameworkMock, where Mock doesn't necessarily refers to Moq, I would like to keep this as a base name for all libraries/packages.

So, my suggestion is:
* EntityFrameworkMock.Shared (not a NuGet package) (I'd like to reserve Core for future EF Core implementations, so: Shared is probably better)
* EntityFrameworkMock.Moq (has NuGet package which includes EntityFrameworkMock.Shared.dll)
* EntityFrameworkMock.NSubstitute (has NuGet package which includes EntityFrameworkMock.Shared.dll)

What'ya think?

**Comment by huysentruitw** [comment]
I would also have to unlist all EntityFrameworkMock packages on nuget.org, but that's a minor thing.

**Comment by pcmichaels** [comment]
Yep - sounds like a plan!

**Comment by huysentruitw** [comment]
Paul, I think I've separated everything I could, so you can go ahead and create a pull-request for NSubstitute based on the latest commit on master.

**Comment by pcmichaels** [comment]
Cheers.  I’m not in front of a PC at this minute, but yesterday I didn’t have any permission to create a branch.  Have you managed to set me up as a collaborator (or whatever permissions apply)?

**Comment by huysentruitw** [comment]
I'd prefer if you could create a pull-request so I can review the changes before merging them. So: fork this repository, create a branch on your fork, commit to that branch and then create a pull-request from that branch to the master of this repository here.

thanks in advance!

**Comment by pcmichaels** [comment]
Yeah, okay.  I’ll create a PR from a fork rather than a branch then.

**Comment by huysentruitw** [comment]
Paul, do you get it working or need any help?

**Comment by pcmichaels** [comment]
It's progressing.  Not had as much time as I expected to spend on it over the last few days.  I've pretty much got it compiling now, though.  Interesting to see exactly how NSubstitute differs from Moq (NSubstitute is pretty much based on a series of static methods).

Anyway, I reckon I'll be submitting the PR by the end of next week.

**Comment by huysentruitw** [comment]
Great work, thank you again :tada:

**Comment by huysentruitw** [comment]
NuGet packages are available
