### ISSUE TITLE
SaveChanges always returns 0

### ISSUE THREAD

**Issue by Higdur** [huysentruitw/entity-framework-mock#19]
The SaveChanges method always returns 0.

https://github.com/huysentruitw/entity-framework-mock/blob/c37489d768c664851d36d377317f3f5ed27daadc/src/EntityFrameworkMock.Shared/DbSetBackingStore.cs#L102

This row should be `return changes.Count;`, not `return _changes.Count;`

**Comment by huysentruitw** [comment]
Fix is included in version 1.0.0.67.

Thanks again!
