### ISSUE TITLE
Why are classes sealed?

### ISSUE THREAD

**Issue by vanrace** [huysentruitw/entity-framework-mock#4]
I very much like your project, I wonder why the classes are sealed? I am a fan of this: [https://medium.com/webcom-engineering-and-product/a-cleaner-way-to-create-mocks-in-net-6e039c3d1db0](url) solution for mocking, which would ofcourse require inheritance..

**Comment by huysentruitw** [comment]
Fixed. Don't forget to star ⭐️ 👍 😄

**Comment by vanrace** [comment]
Awesome! thanks! (star = done)
